//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public Library()
        {
            this.LibraryDetails = new HashSet<LibraryDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupLibraryID { get; set; }
        public Nullable<bool> Action { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Lang { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string Image { get; set; }
    
        public virtual GroupLibrary GroupLibrary { get; set; }
        public virtual ICollection<LibraryDetail> LibraryDetails { get; set; }
    }
}
